trigger: 
  - master 
pool: 
  vmImage: 'windows-latest'
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - task: InlinePowershell@1
    inputs:
      Script: 'Write-Output ''Hello world'''
- job: Job_2  
  displayName: Agent job 2
  pool: server
  steps: 
  - task: ManualValidation@0
    inputs:
      notifyUsers: 'saifeddine.bouaziz@ensi-uma.tn'
      instructions: 'continue?'
  - task: InlinePowershell@1
    inputs:
      Script: 'Write-Output ''authorized'''
