trigger: 
  - master 
pool: 
  vmImage: 'windows-latest' 
stages:  
- stage: stage1
  jobs:
  - job: Job_1
    displayName: Agent job 1
    pool:
      vmImage: windows-latest
    steps:
    - task: InlinePowershell@1
      inputs:
        Script: 'Write-Output ''Hello world''' 
